- hosts: webservers
  become: true
  gather_facts: yes
  name: setup nginx and docker
  roles:
    - { role: nginx, become: True, tags: setup_nginx }
    - { role: docker, become: True, tags: setup_docker }

- hosts: mongo_sharded_cluster
  become: true
  gather_facts: yes
  name: setup mongodb
  roles:
    - { role: mongodb, become: True, tags: setup_mongodb }
