# Multi-stage Dockerfile to build and run a React app in a lightweight container

FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install

ARG API_BASE_URL
ENV API_BASE_URL=${API_BASE_URL}
COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]