---
## using others role (best way)

- ansible.builtin.include_role:
    name: geerlingguy.docker
    apply:
      tags: install_docker

## manuall installation

# - name: "apt-get update"
#   apt:
#     update_cache: yes
#     cache_valid_time: 3600

# - name: Install dependecies
#   apt:
#     name: "{{ docker_packages }}"
#     state: latest
#   tags: install_docker

# - name: Add docker GPG key
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present
#   tags: install_docker

# - name: Add docker repository
#   apt_repository:
#     repo: deb https://download.docker.com/linux/ubuntu focal stable
#     state: present
#   tags: install_docker

# - name: Update apt and install docker-ce
#   apt:
#     name: docker-ce
#     state: latest
#     update_cache: true
#   tags: install_docker

# - name: start docker
#   service:
#     name: docker
#     state: started
#   tags: configure_docker