# Dockerfile to create a lightweight Python 3.11 Alpine environment, install dependencies, and run the main application.

FROM python:3.11-alpine

WORKDIR /app
ADD ./requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt
ADD . /app

CMD [ "python3", "main.py" ]
