all:
  children:
    servers:
      hosts:
          web1:
            ansible_host: 192.168.56.121
            ansible_user: vagrant
            ansible_port: 22
    dbservers:
        hosts:
          db1:
            ansible_host: 192.168.56.122
            ansible_user: vagrant
            ansible_port: 22